export const ERROR_TYPES = {
    VALIDATION: "VALIDATION",
    UNAUTHORIZED: "UNAUTHORIZED",
    CONFLICT: "CONFLICT",
    BAD_REQUEST: "BAD_REQUEST",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorType = typeof ERROR_TYPES[keyof typeof ERROR_TYPES];